options:
  logging: CLOUD_LOGGING_ONLY
  # Allow triggers or submit commands to pass extra substitution keys even if
  # they aren't referenced in this template (e.g., _MEDIA_ROOT).
  # This prevents errors like:
  #   INVALID_ARGUMENT: key "_MEDIA_ROOT" in the substitution data is not matched in the template
  substitution_option: ALLOW_LOOSE

substitutions:
  _REGION: us-west1
  _AR_REPO: cloud-run
  # Optional override tag for additional tagging (e.g. set to $SHORT_SHA in a trigger).
  # If left empty, only the immutable $BUILD_ID tag is used.
  _TAG: ""

  # API
  _SERVICE: podcast-api
  _MEDIA_ROOT: /tmp

  # WORKER (dedicated service for background tasks)
  _WORKER_SERVICE: podcast-worker

  # WEB
  _WEB_SERVICE: podcast-web
  _WEB_DIR: frontend
  _VITE_GOOGLE_CLIENT_ID: '724497178186-kdv8rp3loagl1me3e0v3udlctigq36g9.apps.googleusercontent.com'
  _VITE_API_BASE: https://api.donecast.com/api

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID'

steps:
  # ---------- Preflight: validate secrets and env ----------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: preflight
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        set -x
        echo "==> Verifying gcloud availability"
        gcloud --version

        echo "==> Checking required Secret Manager secrets exist"
        MISSING=0
        REQ_SECRETS=(
          DB_USER
          DB_PASS
          DB_NAME
          SECRET_KEY
          SESSION_SECRET
          GEMINI_API_KEY
          ELEVENLABS_API_KEY
          ASSEMBLYAI_API_KEY
          SPREAKER_API_TOKEN
          SPREAKER_CLIENT_ID
          SPREAKER_CLIENT_SECRET
          GOOGLE_CLIENT_ID
          GOOGLE_CLIENT_SECRET
          STRIPE_SECRET_KEY
          STRIPE_WEBHOOK_SECRET
          AUPHONIC_API_KEY
          r2-account-id
          r2-access-key-id
          r2-secret-access-key
          r2-bucket
          TWILIO_ACCOUNT_SID
          TWILIO_AUTH_TOKEN
          TWILIO_PHONE_NUMBER
          SENTRY_DSN
          VITE_POSTHOG_KEY
        )
        for s in "$${REQ_SECRETS[@]}"; do
          if ! gcloud secrets versions describe latest --secret="$$s" >/dev/null 2>&1; then
            echo "ERROR: Missing secret '$$s' (projects/$PROJECT_ID/secrets/$$s)" >&2
            MISSING=1
          fi
        done
        if [ "$$MISSING" -ne 0 ]; then
          echo "Preflight failed: create the missing secrets above and rerun." >&2
          exit 1
        fi

        # Sanity checks
        test -n "${_REGION}"
        test -n "${_AR_REPO}"
        test -n "$BUILD_ID"

        # Touch optional substitutions to mark them as matched in the template.
        # This avoids errors if submit/trigger passes values for them.
        echo "MEDIA_ROOT=${_MEDIA_ROOT}" >/dev/null || true

  # ---------- Warm cache: pull latest images for cache-from ----------
  - name: gcr.io/cloud-builders/docker
    id: api-cache-pull
    waitFor: ['-']
    entrypoint: bash
    args: ['-c', 'docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest || exit 0']
  - name: gcr.io/cloud-builders/docker
    id: worker-cache-pull
    waitFor: ['-']
    entrypoint: bash
    args: ['-c', 'docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}:latest || exit 0']
  - name: gcr.io/cloud-builders/docker
    id: web-cache-pull
    waitFor: ['-']
    entrypoint: bash
    args: ['-c', 'docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:latest || exit 0']

  # ---------- API & WORKER: build in parallel with BuildKit caching ----------
  - name: gcr.io/cloud-builders/docker
    id: api-build
    waitFor: ['api-cache-pull']
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      [ 'build',
        '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
        '--cache-from', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest',
        '-f', 'Dockerfile.api',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID',
        '.' ]
  - name: gcr.io/cloud-builders/docker
    id: worker-build
    waitFor: ['-']
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      [ 'build',
        '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
        '--cache-from', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}:latest',
        '-f', 'Dockerfile.worker',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}:latest',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}:$BUILD_ID',
        '.' ]
  
  # ---------- API & WORKER: push in parallel ----------
  - name: gcr.io/cloud-builders/docker
    id: api-push
    waitFor: ['api-build']
    entrypoint: sh
    args:
      - -c
      - |
        set -eu
        echo "==> Pushing API images"
        docker push "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest"
        docker push "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID"
  - name: gcr.io/cloud-builders/docker
    id: worker-push
    waitFor: ['worker-build']
    entrypoint: sh
    args:
      - -c
      - |
        set -eu
        echo "==> Pushing Worker images"
        docker push "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}:latest"
        docker push "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}:$BUILD_ID"

  # ---------- WEB: build & push (can run in parallel with API/Worker builds) ----------
  - name: gcr.io/cloud-builders/docker
    id: web-build
    waitFor: ['web-cache-pull']
    entrypoint: sh
    secretEnv:
      - GOOGLE_CLIENT_ID
      - SENTRY_DSN
      - VITE_POSTHOG_KEY
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - -c
      - |
        set -eu
        WEB_DIR='${_WEB_DIR}'
        IMG_LATEST="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:latest"
        IMG_ID="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID"
        OPTIONAL_TAG='${_TAG}'

        echo "==> Verifying context at $${WEB_DIR}"
        ls -la "$${WEB_DIR}"
        test -f "$${WEB_DIR}/package.json"
        du -sh "$${WEB_DIR}" || true

        # Prefer GOOGLE_CLIENT_ID from Secret Manager (provided via secretEnv).
        # Fall back to the substitution if it is set; otherwise emit a warning.
        VGCID="$${GOOGLE_CLIENT_ID:-${_VITE_GOOGLE_CLIENT_ID}}"
        if [ -z "$${VGCID}" ]; then
          echo "WARN: GOOGLE_CLIENT_ID is empty; Google auth will not work" >&2
        fi

        # Use SENTRY_DSN from Secret Manager for frontend error tracking
        SENTRY="$${SENTRY_DSN:-}"

        echo "==> Building web image"
        docker build "$${WEB_DIR}" \
          --file "$${WEB_DIR}/Dockerfile" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from "$${IMG_LATEST}" \
          --build-arg VITE_GOOGLE_CLIENT_ID="$${VGCID}" \
          --build-arg VITE_API_BASE="${_VITE_API_BASE}" \
          --build-arg VITE_SENTRY_DSN="$${SENTRY}" \
          --build-arg VITE_POSTHOG_KEY="$${VITE_POSTHOG_KEY}" \
          --build-arg VITE_POSTHOG_HOST="https://us.i.posthog.com" \
          -t "$${IMG_LATEST}" \
          -t "$${IMG_ID}"

        docker push "$${IMG_LATEST}"
        docker push "$${IMG_ID}"
        if [ -n "$${OPTIONAL_TAG}" ]; then
          EXTRA_TAG="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$${OPTIONAL_TAG}"
          docker tag "$${IMG_ID}" "$${EXTRA_TAG}"
          docker push "$${EXTRA_TAG}"
        fi

  # ---------- API: deploy (waits for api-push) ----------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: api-deploy
    waitFor: ['api-push']
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        # Allow new podcastplusplus domains; keep legacy getpodcastplus for a short transition
        CORS_ALLOWED='https://app.donecast.com;https://donecast.com;https://www.donecast.com;https://api.donecast.com;https://app.podcastplusplus.com;https://podcastplusplus.com;https://www.podcastplusplus.com;https://app.getpodcastplus.com;https://getpodcastplus.com;https://www.getpodcastplus.com'

        echo "==> API deploy prechecks"
        echo "Project: $PROJECT_ID  Region: ${_REGION}  Service: ${_SERVICE}"

        # Verify API image tag exists in Artifact Registry
        API_IMG_PATH="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}"
        if ! gcloud artifacts docker tags list "$${API_IMG_PATH}" --project="$PROJECT_ID" --format='value(tag)' 2>/dev/null | grep -Fx "$BUILD_ID" >/dev/null; then
          echo "ERROR: API image tag not found: $${API_IMG_PATH}:$BUILD_ID. Ensure image push succeeded." >&2
          exit 1
        fi

        deploy_once() {
          gcloud run deploy ${_SERVICE} \
            --project=$PROJECT_ID \
            --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID \
            --region=${_REGION} \
            --platform=managed \
            --timeout=3600 \
            --cpu=1 \
            --memory=2Gi \
            --min-instances=0 \
            --max-instances=10 \
            --concurrency=100 \
            --execution-environment=gen2 \
            --cpu-boost \
            --add-cloudsql-instances=podcast612:us-west1:podcast-db \
            --command=sh \
            --args=-c,"exec python -m uvicorn api.app:app --host 0.0.0.0 --port $${PORT:-8080} --log-level info" \
            --set-env-vars="CLOUDPOD_MAX_MIX_BUFFER_BYTES=536870912,INSTANCE_CONNECTION_NAME=podcast612:us-west1:podcast-db,GOOGLE_CLOUD_PROJECT=podcast612,APP_ENV=production,CORS_ALLOWED_ORIGINS=https://donecast.com;https://www.donecast.com;https://app.donecast.com;https://api.donecast.com;https://podcastplusplus.com;https://www.podcastplusplus.com;https://app.podcastplusplus.com;https://api.podcastplusplus.com;https://getpodcastplus.com;https://www.getpodcastplus.com;https://app.getpodcastplus.com,DB_POOL_SIZE=20,DB_MAX_OVERFLOW=20,DB_POOL_RECYCLE=1800,DB_POOL_TIMEOUT=10,DB_POOL_PRE_PING=true,DB_CONNECT_TIMEOUT=60,DB_STATEMENT_TIMEOUT_MS=300000,STORAGE_BACKEND=r2,AI_PROVIDER=gemini,VERTEX_PROJECT=podcast612,VERTEX_LOCATION=us-central1,VERTEX_MODEL=gemini-2.5-flash-lite,GEMINI_MODEL=gemini-2.5-flash,TASKS_URL_BASE=https://api.donecast.com,WORKER_URL_BASE=https://assemble.donecast.com,ENABLE_LOCAL_WORKER=false,ENABLE_CELERY=false,ADMIN_EMAIL=scott@scottgerhardt.com,MEDIA_ROOT=/tmp,OAUTH_BACKEND_BASE=https://api.donecast.com,MEDIA_BUCKET=ppp-media-us-west1,TRANSCRIPTS_BUCKET=ppp-transcripts-us-west1,GCS_CHUNK_MB=32,SMTP_HOST=smtp.mailgun.org,SMTP_PORT=587,SMTP_USER=admin@donecast.com,SMTP_FROM=no-reply@donecast.com,DISABLE_STARTUP_MIGRATIONS=1,FEEDBACK_SHEET_ID=1dnIMPYvaoGe5hRdJ9W1k9CFua3y2I6aW55BLDMxH_6k,GOOGLE_SHEETS_ENABLED=true" \
            --set-secrets="DB_USER=DB_USER:latest,DB_PASS=DB_PASS:latest,DB_NAME=DB_NAME:latest,DATABASE_URL=DATABASE_URL:latest,SECRET_KEY=SECRET_KEY:latest,SESSION_SECRET=SESSION_SECRET:latest,GCS_SIGNER_KEY_JSON=gcs-signer-key:latest,AUPHONIC_API_KEY=AUPHONIC_API_KEY:latest,R2_ACCOUNT_ID=r2-account-id:latest,R2_ACCESS_KEY_ID=r2-access-key-id:latest,R2_SECRET_ACCESS_KEY=r2-secret-access-key:latest,R2_BUCKET=r2-bucket:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,ELEVENLABS_API_KEY=ELEVENLABS_API_KEY:latest,ASSEMBLYAI_API_KEY=ASSEMBLYAI_API_KEY:latest,TASKS_AUTH=TASKS_AUTH:latest,SMTP_PASS=SMTP_PASS:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_PUBLISHABLE_KEY=STRIPE_PUBLISHABLE_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,SPREAKER_API_TOKEN=SPREAKER_API_TOKEN:latest,SPREAKER_CLIENT_ID=SPREAKER_CLIENT_ID:latest,SPREAKER_CLIENT_SECRET=SPREAKER_CLIENT_SECRET:latest,TWILIO_ACCOUNT_SID=TWILIO_ACCOUNT_SID:latest,TWILIO_AUTH_TOKEN=TWILIO_AUTH_TOKEN:latest,TWILIO_PHONE_NUMBER=TWILIO_PHONE_NUMBER:latest,SENTRY_DSN=SENTRY_DSN:latest,POSTHOG_API_KEY=VITE_POSTHOG_KEY:latest" \
            --quiet
        }

        # Retry deploy to handle transient API errors
        ATTEMPT=0
        MAX_ATTEMPTS=3
        while [ "$${ATTEMPT}" -lt "$${MAX_ATTEMPTS}" ]; do
          if deploy_once; then
            echo "==> API deploy succeeded"
            # CRITICAL: Route 100% traffic to latest revision
            gcloud run services update-traffic ${_SERVICE} \
              --project=$PROJECT_ID \
              --region=${_REGION} \
              --to-latest \
              --quiet
            exit 0
          fi
          ATTEMPT=$((ATTEMPT+1))
          if [ "$${ATTEMPT}" -lt "$${MAX_ATTEMPTS}" ]; then
            SLEEP=$((ATTEMPT*5))
            echo "WARN: API deploy attempt $${ATTEMPT} failed, retrying in $${SLEEP}s ..." >&2
            sleep "$${SLEEP}"
          fi
        done
        echo "ERROR: API deploy failed after $${MAX_ATTEMPTS} attempts." >&2
        exit 1

  # ---------- WORKER: deploy (waits for worker-push) ----------
  # NOTE: Worker deployment is disabled as the worker is mostly obsolete and background jobs
  # have been offloaded to external servers. To re-enable, uncomment the step below.
  # Option B (cold standby): If you need to keep the worker as a cold standby, uncomment
  # and update the deploy_worker() function with: --cpu=2 --memory=4Gi --concurrency=5
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  #   id: worker-deploy
  #   waitFor: ['worker-push']
  #   entrypoint: bash
  #   args:
  #     - -c
  #     - |
  #       set -euo pipefail
  #       
  #       echo "==> Worker deploy prechecks"
  #       echo "Project: $PROJECT_ID  Region: ${_REGION}  Service: ${_WORKER_SERVICE}"
  #       
  #       # Verify worker image tag exists in Artifact Registry
  #       WORKER_IMG_PATH="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}"
  #       if ! gcloud artifacts docker tags list "$${WORKER_IMG_PATH}" --project="$PROJECT_ID" --format='value(tag)' 2>/dev/null | grep -Fx "$BUILD_ID" >/dev/null; then
  #         echo "ERROR: Worker image tag not found: $${WORKER_IMG_PATH}:$BUILD_ID. Ensure image push succeeded." >&2
  #         exit 1
  #       fi
  #       
  #       deploy_worker() {
  #         # Worker needs same configuration as API to access database, GCS, etc.
  #         # Note: PORT env var is set by Cloud Run, Dockerfile.worker uses ${PORT:-8080}
  #         gcloud run deploy ${_WORKER_SERVICE} \
  #           --project=$PROJECT_ID \
  #           --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WORKER_SERVICE}:$BUILD_ID \
  #           --region=${_REGION} \
  #           --platform=managed \
  #           --timeout=3600 \
  #           --cpu=2 \
  #           --memory=4Gi \
  #           --min-instances=0 \
  #           --max-instances=3 \
  #           --concurrency=5 \
  #           --execution-environment=gen2 \
  #           --add-cloudsql-instances=podcast612:us-west1:podcast-db \
  #           --set-env-vars="CLOUDPOD_MAX_MIX_BUFFER_BYTES=536870912,MEDIA_ROOT=/tmp,INSTANCE_CONNECTION_NAME=podcast612:us-west1:podcast-db,GOOGLE_CLOUD_PROJECT=podcast612,TASKS_LOCATION=us-west1,TASKS_QUEUE=ppp-queue,APP_ENV=production,AI_PROVIDER=vertex,VERTEX_PROJECT=podcast612,VERTEX_LOCATION=us-central1,VERTEX_MODEL=gemini-2.5-flash-lite,USE_CLOUD_TASKS=1,DB_POOL_SIZE=5,DB_MAX_OVERFLOW=2,DB_POOL_RECYCLE=300,DB_POOL_TIMEOUT=15,GCS_CHUNK_MB=32,MEDIA_BUCKET=ppp-media-us-west1,TRANSCRIPTS_BUCKET=ppp-transcripts-us-west1,STORAGE_BACKEND=r2" \
  #           --set-secrets="DB_USER=DB_USER:latest,DB_PASS=DB_PASS:latest,DB_NAME=DB_NAME:latest,DATABASE_URL=DATABASE_URL:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,ELEVENLABS_API_KEY=ELEVENLABS_API_KEY:latest,ASSEMBLYAI_API_KEY=ASSEMBLYAI_API_KEY:latest,TASKS_AUTH=TASKS_AUTH:latest,GCS_SIGNER_KEY_JSON=gcs-signer-key:latest,AUPHONIC_API_KEY=AUPHONIC_API_KEY:latest,R2_ACCOUNT_ID=r2-account-id:latest,R2_ACCESS_KEY_ID=r2-access-key-id:latest,R2_SECRET_ACCESS_KEY=r2-secret-access-key:latest,R2_BUCKET=r2-bucket:latest" \
  #           --quiet
  #       }
  #       
  #       # Retry deploy to handle transient API errors
  #       ATTEMPT=0
  #       MAX_ATTEMPTS=3
  #       while [ "$${ATTEMPT}" -lt "$${MAX_ATTEMPTS}" ]; do
  #         if deploy_worker; then
  #           echo "==> Worker deploy succeeded"
  #           # Ensure traffic routes to latest revision
  #           gcloud run services update-traffic ${_WORKER_SERVICE} \
  #             --project=$PROJECT_ID \
  #             --region=${_REGION} \
  #             --to-latest \
  #             --quiet
  #           exit 0
  #         fi
  #         ATTEMPT=$((ATTEMPT+1))
  #         if [ "$${ATTEMPT}" -lt "$${MAX_ATTEMPTS}" ]; then
  #           SLEEP=$((ATTEMPT*5))
  #           echo "WARN: Worker deploy attempt $${ATTEMPT} failed, retrying in $${SLEEP}s ..." >&2
  #           sleep "$${SLEEP}"
  #         fi
  #       done
  #       echo "ERROR: Worker deploy failed after $${MAX_ATTEMPTS} attempts." >&2
  #       exit 1

  # ---------- WEB: deploy (waits for web-build) ----------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: web-deploy
    waitFor: ['web-build']
    entrypoint: gcloud
    args:
      [ 'run', 'deploy', '${_WEB_SERVICE}',
        '--project=$PROJECT_ID',
        '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID',
        '--region=${_REGION}',
        '--platform=managed',
        '--execution-environment=gen2',
        '--cpu=1',
        '--memory=1Gi',
        '--concurrency=200',
        '--min-instances=0',
        '--max-instances=5',
        '--allow-unauthenticated',
        '--quiet' ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
    - versionName: projects/$PROJECT_ID/secrets/SENTRY_DSN/versions/latest
      env: SENTRY_DSN
    - versionName: projects/$PROJECT_ID/secrets/VITE_POSTHOG_KEY/versions/latest
      env: VITE_POSTHOG_KEY
