# Frontend-Only Cloud Build Configuration
# Usage: gcloud builds submit --config=cloudbuild-frontend-only.yaml --region=us-west1

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

substitutions:
  _REGION: us-west1
  _AR_REPO: cloud-run
  _WEB_SERVICE: podcast-web
  _WEB_DIR: frontend
  _VITE_GOOGLE_CLIENT_ID: '724497178186-kdv8rp3loagl1me3e0v3udlctigq36g9.apps.googleusercontent.com'
  _VITE_API_BASE: https://api.podcastplusplus.com

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID'

steps:
  # ---------- WEB: build & push ----------
  - name: gcr.io/cloud-builders/docker
    id: web-build
    entrypoint: sh
    secretEnv:
      - GOOGLE_CLIENT_ID
    args:
      - -c
      - |
        set -eu
        WEB_DIR='${_WEB_DIR}'
        IMG_LATEST="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:latest"
        IMG_ID="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID"

        echo "==> Frontend-Only Build"
        echo "==> Verifying context at $${WEB_DIR}"
        ls -la "$${WEB_DIR}"
        test -f "$${WEB_DIR}/package.json"
        du -sh "$${WEB_DIR}" || true

        # Prefer GOOGLE_CLIENT_ID from Secret Manager (provided via secretEnv).
        # Fall back to the substitution if it is set; otherwise emit a warning.
        VGCID="$${GOOGLE_CLIENT_ID:-${_VITE_GOOGLE_CLIENT_ID}}"
        if [ -z "$${VGCID}" ]; then
          echo "WARN: GOOGLE_CLIENT_ID is empty; Google auth will not work" >&2
        fi

        echo "==> Building web image"
        docker build "$${WEB_DIR}" \
          --file "$${WEB_DIR}/Dockerfile" \
          --build-arg VITE_GOOGLE_CLIENT_ID="$${VGCID}" \
          --build-arg VITE_API_BASE="${_VITE_API_BASE}" \
          -t "$${IMG_LATEST}" \
          -t "$${IMG_ID}"

        echo "==> Pushing web images"
        docker push "$${IMG_LATEST}"
        docker push "$${IMG_ID}"

  # ---------- WEB: deploy ----------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: web-deploy
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        set -x
        
        echo "==> Deploying frontend to Cloud Run"
        echo "Project: $PROJECT_ID  Region: ${_REGION}  Service: ${_WEB_SERVICE}"
        echo "Image: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID"
        
        # Verify we can list Run services (permission sanity)
        if ! gcloud run services list --project=$PROJECT_ID --region=${_REGION} --platform=managed --format='value(name)' >/dev/null 2>&1; then
          echo "ERROR: Unable to list Cloud Run services in project=$PROJECT_ID region=${_REGION}. Check Cloud Build SA permissions." >&2
          exit 1
        fi

        # Deploy
        gcloud run deploy ${_WEB_SERVICE} \
          --project=$PROJECT_ID \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated

        echo "==> ✓ Frontend deployment complete!"
        
        # Show service URL
        gcloud run services describe ${_WEB_SERVICE} \
          --project=$PROJECT_ID \
          --region=${_REGION} \
          --platform=managed \
          --format="value(status.url)"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
