options:
  logging: CLOUD_LOGGING_ONLY
  # Allow triggers or submit commands to pass extra substitution keys even if
  # they aren't referenced in this template (e.g., _MEDIA_ROOT).
  # This prevents errors like:
  #   INVALID_ARGUMENT: key "_MEDIA_ROOT" in the substitution data is not matched in the template
  substitution_option: ALLOW_LOOSE

substitutions:
  _REGION: us-west1
  _AR_REPO: cloud-run
  # Optional override tag for additional tagging (e.g. set to $SHORT_SHA in a trigger).
  # If left empty, only the immutable $BUILD_ID tag is used.
  _TAG: ""

  # API
  _SERVICE: podcast-api
  _MEDIA_ROOT: /tmp

  # WEB
  _WEB_SERVICE: podcast-web
  _WEB_DIR: frontend
  _VITE_GOOGLE_CLIENT_ID: '724497178186-kdv8rp3loagl1me3e0v3udlctigq36g9.apps.googleusercontent.com'
  _VITE_API_BASE: https://api.podcastplusplus.com

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID'

steps:
  # ---------- Preflight: validate secrets and env ----------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: preflight
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        set -x
        echo "==> Verifying gcloud availability"
        gcloud --version

        echo "==> Checking required Secret Manager secrets exist"
        MISSING=0
        REQ_SECRETS=(
          DB_USER
          DB_PASS
          DB_NAME
          SECRET_KEY
          SESSION_SECRET
          GEMINI_API_KEY
          ELEVENLABS_API_KEY
          ASSEMBLYAI_API_KEY
          SPREAKER_API_TOKEN
          SPREAKER_CLIENT_ID
          SPREAKER_CLIENT_SECRET
          GOOGLE_CLIENT_ID
          GOOGLE_CLIENT_SECRET
          STRIPE_SECRET_KEY
          STRIPE_WEBHOOK_SECRET
        )
        for s in "$${REQ_SECRETS[@]}"; do
          if ! gcloud secrets versions describe latest --secret="$$s" >/dev/null 2>&1; then
            echo "ERROR: Missing secret '$$s' (projects/$PROJECT_ID/secrets/$$s)" >&2
            MISSING=1
          fi
        done
        if [ "$$MISSING" -ne 0 ]; then
          echo "Preflight failed: create the missing secrets above and rerun." >&2
          exit 1
        fi

        # Sanity checks
        test -n "${_REGION}"
        test -n "${_AR_REPO}"
        test -n "$BUILD_ID"

        # Touch optional substitutions to mark them as matched in the template.
        # This avoids errors if submit/trigger passes values for them.
        echo "MEDIA_ROOT=${_MEDIA_ROOT}" >/dev/null || true

  # ---------- API: build & push ----------
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID',
        '.' ]
  - name: gcr.io/cloud-builders/docker
    id: api-push
    entrypoint: sh
    args:
      - -c
      - |
        set -eu
        echo "==> Pushing API images"
        docker push "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest"
        docker push "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID"

  # ---------- WEB: build & push ----------
  - name: gcr.io/cloud-builders/docker
    id: web-build
    entrypoint: sh
    secretEnv:
      - GOOGLE_CLIENT_ID
    args:
      - -c
      - |
        set -eu
        WEB_DIR='${_WEB_DIR}'
        IMG_LATEST="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:latest"
        IMG_ID="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID"
        OPTIONAL_TAG='${_TAG}'

        echo "==> Verifying context at $${WEB_DIR}"
        ls -la "$${WEB_DIR}"
        test -f "$${WEB_DIR}/package.json"
        du -sh "$${WEB_DIR}" || true

        # Prefer GOOGLE_CLIENT_ID from Secret Manager (provided via secretEnv).
        # Fall back to the substitution if it is set; otherwise emit a warning.
        VGCID="$${GOOGLE_CLIENT_ID:-${_VITE_GOOGLE_CLIENT_ID}}"
        if [ -z "$${VGCID}" ]; then
          echo "WARN: GOOGLE_CLIENT_ID is empty; Google auth will not work" >&2
        fi

        echo "==> Building web image"
        docker build "$${WEB_DIR}" \
          --file "$${WEB_DIR}/Dockerfile" \
          --build-arg VITE_GOOGLE_CLIENT_ID="$${VGCID}" \
          --build-arg VITE_API_BASE="${_VITE_API_BASE}" \
          -t "$${IMG_LATEST}" \
          -t "$${IMG_ID}"

        docker push "$${IMG_LATEST}"
        docker push "$${IMG_ID}"
        if [ -n "$${OPTIONAL_TAG}" ]; then
          EXTRA_TAG="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$${OPTIONAL_TAG}"
          docker tag "$${IMG_ID}" "$${EXTRA_TAG}"
          docker push "$${EXTRA_TAG}"
        fi

  # ---------- API: deploy ----------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: api-deploy
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        set -x
        gcloud config set core/verbosity debug
        # Allow new podcastplusplus domains; keep legacy getpodcastplus for a short transition
        CORS_ALLOWED='https://app.podcastplusplus.com;https://podcastplusplus.com;https://www.podcastplusplus.com;https://app.getpodcastplus.com;https://getpodcastplus.com;https://www.getpodcastplus.com'

        echo "==> API deploy prechecks"
        echo "Project: $PROJECT_ID  Region: ${_REGION}  Service: ${_SERVICE}"
        echo "CORS_ALLOWED_ORIGINS length: $${#CORS_ALLOWED}"

        # Verify we can list Run services (permission sanity)
        if ! gcloud run services list --project=$PROJECT_ID --region=${_REGION} --platform=managed --format='value(name)' >/dev/null 2>&1; then
          echo "ERROR: Unable to list Cloud Run services in project=$PROJECT_ID region=${_REGION}. Check Cloud Build SA permissions (roles/run.admin)." >&2
          exit 1
        fi

        # Verify API image tag exists in Artifact Registry
        API_IMG_PATH="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}"
        if ! gcloud artifacts docker tags list "$${API_IMG_PATH}" --project="$PROJECT_ID" --format='value(tag)' | grep -Fx "$BUILD_ID" >/dev/null; then
          echo "ERROR: API image tag not found: $${API_IMG_PATH}:$BUILD_ID. Ensure image push succeeded." >&2
          gcloud artifacts docker tags list "$${API_IMG_PATH}" --project="$PROJECT_ID" --format='table(tag,digest)'
          exit 1
        fi

        deploy_once() {
          gcloud run deploy ${_SERVICE} \
            --project=$PROJECT_ID \
            --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$BUILD_ID \
            --region=${_REGION} \
            --platform=managed \
            --timeout=3600 \
            --cpu=2 \
            --memory=4Gi \
            --min-instances=1 \
            --max-instances=10 \
            --concurrency=80 \
            --no-cpu-throttling \
            --execution-environment=gen2 \
            --update-env-vars="CLOUDPOD_MAX_MIX_BUFFER_BYTES=2147483648" \
            --update-secrets="GCS_SIGNER_KEY_JSON=gcs-signer-key:latest"
        }

        # Retry deploy to handle transient API errors
        ATTEMPT=0
        until [ "$${ATTEMPT}" -ge 3 ]; do
          if deploy_once; then
            echo "==> API deploy succeeded"
            break
          fi
          ATTEMPT=$((ATTEMPT+1))
          SLEEP=$((ATTEMPT*5))
          echo "WARN: API deploy attempt $${ATTEMPT} failed, retrying in $${SLEEP}s ..." >&2
          sleep "$${SLEEP}"
        done
        if [ "$${ATTEMPT}" -ge 3 ]; then
          echo "ERROR: API deploy failed after retries. See logs above for detailed gcloud error output." >&2
          exit 1
        fi
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: web-deploy
    entrypoint: gcloud
    args:
      [ 'run', 'deploy', '${_WEB_SERVICE}',
        '--project=$PROJECT_ID',
        '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_SERVICE}:$BUILD_ID',
        '--region=${_REGION}',
        '--platform=managed',
        '--allow-unauthenticated' ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
